vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    # mappings:
    #     recipe_files:
    #         uri_prefix: '/images/docs'
    #         upload_destination: '%kernel.project_dir%/public/images/docs'
    #         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
