controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

dyg81modalbundle:
    resource: "@Dyg81ModalBundle/src/Controller/"
    type:     annotation